
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class showsubs extends javax.swing.JInternalFrame {

    /**
     * Creates new form showsubs
     */
    String uname_1;
    String tid2;
    public showsubs(String uname,String tid1) {
        initComponents();
        uname_1=uname;
        tid2=tid1;
        filltable1();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ttt = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        ttt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(ttt);

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 void filltable1()
  {
          try
    {
       
          
             Class.forName("oracle.jdbc.OracleDriver");
          String str = "jdbc:oracle:thin:@localhost:1521:";
          Connection con = DriverManager.getConnection(str,"ANKITA","ANKITA");
            String s="select subject.subject_id,subject.subject_name from assignteacher,subject where tid=? and subject.subject_id=assignteacher.subject_id";
              PreparedStatement ps=con.prepareStatement(s);
              ps.setString(1,tid2);
              ResultSet rs=ps.executeQuery();
           Vector heading=new Vector();
         heading.add("SUBJECT ID");
          heading.add("SUBJECT NAME");
           
           Vector row=new Vector();
             
            
              while(rs.next())
              {
                
                    String s1=rs.getString("subject_id");
                     String s2=rs.getString("subject_name");
                  Vector cell=new Vector();
                    cell.add(s1);
                  cell.add(s2);
                  
                 
                  row.add(cell);
                 
                
              }
                DefaultTableModel model=new DefaultTableModel(row,heading);
           ttt.setModel(model);   
              }
    
    catch(Exception ex)
    {
        ex.printStackTrace();
    }
      
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable ttt;
    // End of variables declaration//GEN-END:variables
}
