
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import javax.swing.DefaultCellEditor;
import javax.swing.JCheckBox;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


/**
 *
 * @author Admin
 */
public class showattendance extends javax.swing.JInternalFrame {
    Vector data;
  ArrayList course=new ArrayList();
  ArrayList subject=new ArrayList();
   ArrayList student_pr=new ArrayList();
   boolean flag;
   boolean flag1;
   
 String uname_1;
    String tid2;
    public showattendance(String uname,String tid1) {
        initComponents();
         uname_1=uname;
        tid2=tid1;
        
      
                    flag=true;
                    flag1=true;
                   
                    fillcourses();
                   
      
    }
    
    
    
    
    
    void filltable2()
    {
          Date date1=new Date();
         SimpleDateFormat d=new SimpleDateFormat("dd-MM-yyyy");  
         String cd=d.format(date1);
                try
    {
         
     
             Class.forName("oracle.jdbc.OracleDriver");
          String str = "jdbc:oracle:thin:@localhost:1521:";
          Connection con = DriverManager.getConnection(str,"ANKITA","ANKITA");
            String s="select * from attendance where course_id=? and subject_id=? and date1=?";
              PreparedStatement ps=con.prepareStatement(s);
                int id3=cb1.getSelectedIndex();
          String cid[]= (String []) course.get(id3);
          String cidd=cid[0];
          
          /**************************************/
          
          /****************************************/
          
        int id1=cb2.getSelectedIndex();
        String sid[]= (String []) subject.get(id1);
        String sidd=sid[0];
        System.out.println("courseid"+cidd+"subjectid"+sidd+"date"+cd);
                
        ps.setString(1, cidd);
        ps.setString(2, sidd);
        ps.setString(3, cd);
         
        ResultSet rs=ps.executeQuery();
        Vector heading=new Vector();
        heading.add("STUDENT ID");
        heading.add("STUDENT NAME");
           

        Vector row=new Vector();
             
            
              while(rs.next())
              {
                  String s1=rs.getString("sid");
                  String s2=rs.getString("course_id");
                  System.out.println("SSSSS "+s1+"ddddd "+s2);
                  Vector cell=new Vector();
                  cell.add(s1);
                  cell.add(s2);
                
                  row.add(cell);
                 
                
              }
               
                DefaultTableModel model=new DefaultTableModel(row,heading);
           ttt1.setModel(model); 
           con.close(); 
              }
               
    
    catch(Exception ex)
    {
        ex.printStackTrace();
    } 
    }
    
    
    
    void fillsubjects()
    {
         try{
              cb2.removeAllItems();
              if(flag !=false)
              {
              Class.forName("oracle.jdbc.OracleDriver");
          String str = "jdbc:oracle:thin:@localhost:1521:";
          Connection con = DriverManager.getConnection(str,"ANKITA","ANKITA");
          String s="select * from subject where course_id=?";
          PreparedStatement ps=con.prepareStatement(s);
        String c_array[] = new String[2];
        int index2 = cb1.getSelectedIndex();
        c_array = (String[]) course.get(index2);
        String course_id = c_array[0];
        ps.setString(1,course_id);
          
         ResultSet rs= ps.executeQuery();
         while(rs.next()){
             String sub_array[]=new String[3];
             sub_array[0]=rs.getString("subject_id");
             sub_array[1]=rs.getString("subject_name");
              sub_array[2]=rs.getString("course_id");
            String cname=rs.getString("subject_name");
            subject.add(sub_array);
            cb2.addItem(cname);
         }
          flag1=true; con.close();
              }
           
    }
    catch(Exception e){
        e.printStackTrace();
    }
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cb1 = new javax.swing.JComboBox();
        cb2 = new javax.swing.JComboBox();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ttt = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        ttt1 = new javax.swing.JTable();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jCheckBox1.setText("jCheckBox1");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Show Attendance");

        jLabel1.setText("Course ID");

        jLabel2.setText("Subject ID");

        cb1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb1ItemStateChanged(evt);
            }
        });
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });

        cb2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb2ItemStateChanged(evt);
            }
        });
        cb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Present");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Absent");

        ttt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ttt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tttMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ttt);

        ttt1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(ttt1);

        jLabel4.setText("SID");

        jLabel5.setText("SNAME");

        jButton1.setText("save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cb2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(69, 69, 69)
                        .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addComponent(jButton1)
                .addGap(269, 269, 269))
            .addGroup(layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(jRadioButton1)
                                .addGap(67, 67, 67)
                                .addComponent(jRadioButton2)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 199, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 72, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(561, 561, 561))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cb2ActionPerformed

    private void cb1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb1ItemStateChanged
        // TODO add your handling code here:
        if(flag != false)
        {
            fillsubjects();
           int count=2;
        }
//        try{
//    
//            if(flag!=false)
//            {
//              Class.forName("oracle.jdbc.OracleDriver");
//          String str = "jdbc:oracle:thin:@localhost:1521:";
//          Connection con = DriverManager.getConnection(str,"ANKITA","ANKITA");
//          String s="select * from subject ";
//          PreparedStatement ps=con.prepareStatement(s);
//         int id=cb1.getSelectedIndex();
//          String sid[]= (String []) course.get(id);
//          String sidd=sid[0];
//          ps.setString(1,sidd);
//          
//         ResultSet rs= ps.executeQuery();
//         while(rs.next()){
//             String c_array[]=new String[3];
//             c_array[0]=rs.getString("subject_id");
//             c_array[1]=rs.getString("subject_name");
//              c_array[0]=rs.getString("course_id");
//            String cname= rs.getString("subject_id");
//            subject.add(c_array);
//            cb1.addItem(cname);
//         }
//          con.close();
//          
//    }}
//    catch(Exception e){
//        e.printStackTrace();
//    }
        
    }//GEN-LAST:event_cb1ItemStateChanged

    private void cb2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb2ItemStateChanged
    
        
//      try{
//       int id=cb2.getSelectedIndex();
//          String sid[]= (String []) subject.get(id);
//            String subid=sid[0];
//              Class.forName("oracle.jdbc.OracleDriver");
//          String str = "jdbc:oracle:thin:@localhost:1521:";
//          Connection con = DriverManager.getConnection(str,"ANKITA","ANKITA");
//          String s="select course.course_id,course.course_name from course,subject where course.course_id = subject.course_id and subject.subject_id=?";
//          PreparedStatement ps=con.prepareStatement(s);
//       ps.setString(1,subid);
//         ResultSet rs= ps.executeQuery();
//         
//         while(rs.next()){
//             String c_array[]=new String[2];
//             c_array[0]=rs.getString("course_id");
//             c_array[1]=rs.getString("course_name");
//            String cname= rs.getString("course_name");
//            course.add(c_array);
//            cb1.addItem(cname);
//         }
//          con.close();
//          
//    }
//    catch(Exception e){
//        e.printStackTrace();
//    }
//        
    }//GEN-LAST:event_cb2ItemStateChanged

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
        // TODO add your handling code here:
//          try{
//       int id=cb2.getSelectedIndex();
//          String sid[]= (String []) subject.get(id);
//            String subid=sid[0];
//              Class.forName("oracle.jdbc.OracleDriver");
//          String str = "jdbc:oracle:thin:@localhost:1521:";
//          Connection con = DriverManager.getConnection(str,"ANKITA","ANKITA");
//          String s="select course.course_id,course.course_name from course,subject where course.course_id = subject.course_id and subject.subject_id=?";
//          PreparedStatement ps=con.prepareStatement(s);
//       ps.setString(1,subid);
//         ResultSet rs= ps.executeQuery();
//         
//         while(rs.next()){
//             String c_array[]=new String[2];
//             c_array[0]=rs.getString("course_id");
//             c_array[1]=rs.getString("course_name");
//            String cname= rs.getString("course_name");
//            course.add(c_array);
//            cb1.addItem(cname);
//         }
//          con.close();
//          
//    }
//    catch(Exception e){
//        e.printStackTrace();
//    }
//        
//    
    }//GEN-LAST:event_cb1ActionPerformed

    private void tttMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tttMouseClicked
        // TODO add your handling code here:
          
       TableModel m1= ttt.getModel();
     int r=  ttt.getSelectedRow();
   String z=(String)  m1.getValueAt(r, 0);
    String y=(String) m1.getValueAt(r,1);
    
      
t1.setText(z);  
t2.setText(y); 

      
    }//GEN-LAST:event_tttMouseClicked

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
      try
         {
             String c_array[] = new String[2];
              int id=cb1.getSelectedIndex();
          String c[]=   (String [])course.get(id);
          String course_id = c[0];
          
           String sub_array[] = new String[3];
             int id2=cb2.getSelectedIndex();
          String c1[]=   (String [])subject.get(id2);
          String sub_id = c1[0];
          
          
            Date date1=new Date();
         SimpleDateFormat d=new SimpleDateFormat("dd-MM-yyyy");  
         String cd=d.format(date1);
           String s_id=t1.getText();
              Class.forName("oracle.jdbc.OracleDriver");
          String str = "jdbc:oracle:thin:@localhost:1521:";
          Connection con = DriverManager.getConnection(str,"ANKITA","ANKITA");
          String s="insert into attendance values(?,?,?,?,?)";
          PreparedStatement ps=con.prepareStatement(s);
           ps.setString(1,"");
                      ps.setString(2,sub_id);

                                ps.setString(3,s_id);
           ps.setString(4,cd);
             ps.setString(5,course_id);


           ResultSet rs=ps.executeQuery();
   
    
      filltable2();
      filltable(); 
      con.close();
    }//GEN-LAST:event_jRadioButton1ActionPerformed
 catch(Exception ex)
 {
     ex.printStackTrace();
 }}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        filltable();
    }//GEN-LAST:event_jButton1ActionPerformed

   void fillcourses(){
       try
         {
           
     
          
              Class.forName("oracle.jdbc.OracleDriver");
          String str = "jdbc:oracle:thin:@localhost:1521:";
          Connection con = DriverManager.getConnection(str,"ANKITA","ANKITA");
          String s="select course.course_id,course.course_name from teacher,ASSIGNTEACHER,subject,course where ASSIGNTEACHER.tid=teacher.tid and ASSIGNTEACHER.subject_id=subject.subject_id and subject.course_id=course.course_id and teacher.tid=?";
          PreparedStatement ps=con.prepareStatement(s);
       
          ps.setString(1,tid2);
 
          
          ResultSet rs=ps.executeQuery();
           while(rs.next()){
             String c_array[]=new String[2];
             c_array[0]=rs.getString("course_id");
             c_array[1]=rs.getString("course_name");
            String cname= rs.getString("course_name");
            course.add(c_array);
            cb1.addItem(cname);
         }
           for(int i=0;i<course.size();i++)
           {
               String hh[] = (String[]) course.get(i);
           }
          con.close();
          
         }
         catch(Exception e)
         {
             e.printStackTrace();
         }
    
}
   void fillstudents(){
//    try{
//     
//            
//              Class.forName("oracle.jdbc.OracleDriver");
//          String str = "jdbc:oracle:thin:@localhost:1521:";
//          Connection con = DriverManager.getConnection(str,"ANKITA","ANKITA");
//          String s="select * from student_pr";
//          PreparedStatement ps=con.prepareStatement(s);
//         
//         ResultSet rs= ps.executeQuery();
//         while(rs.next()){
//             String c_array[]=new String[8];
//             c_array[0]=rs.getString("sid");
//              c_array[1]=rs.getString("sname");
//           
//               c_array[2]=rs.getString("address"); 
//               c_array[3]=rs.getString("contactno");
//                 c_array[4]=rs.getString("username");
//                   c_array[5]=rs.getString("password");
//                     c_array[6]=rs.getString("emailid");
//                       c_array[7]=rs.getString("course_id");
//            String cname= rs.getString("sid");
//            course.add(c_array);
//            cb3.addItem(cname);
//         }
//          con.close();
//          
//    }
//    catch(Exception e){
//        e.printStackTrace();
//    }
}
   void filltable()
   {
     
              try
    {
       
          
             Class.forName("oracle.jdbc.OracleDriver");
          String str = "jdbc:oracle:thin:@localhost:1521:";
          Connection con = DriverManager.getConnection(str,"ANKITA","ANKITA");
            String s="select * from student_pr where course_id=? and sid not in (select sid from attendance where subject_id=? and date1=?)";
              PreparedStatement ps=con.prepareStatement(s);
              int id=cb1.getSelectedIndex();
          String cid[]= (String []) course.get(id);
          String cidd=cid[0];
         
          Date date1=new Date();
         SimpleDateFormat d=new SimpleDateFormat("dd-MM-yyyy");  
         String cd=d.format(date1);
            int id1=cb2.getSelectedIndex();
          String sid[]= (String []) subject.get(id1);
          String sidd=sid[0];
           ps.setString(1,cidd.trim());
            ps.setString(2,sidd.trim());
              ps.setString(3,cd);
         
         System.out.println("ourse_id"+cidd+"sub_id"+sidd+"date"+cd);
               
              ResultSet rs=ps.executeQuery();
           Vector heading=new Vector();
         heading.add("STUDENT ID");
          heading.add("STUDENT NAME");
           

                   
           
           Vector row=new Vector();
             
            
              while(rs.next())
              {
                  String s1=rs.getString("sid");
                  String s2=rs.getString("sname");
                   String s3=rs.getString("address");
                    String s4=rs.getString("contactno");
                     String s5=rs.getString("username");
                      String s6=rs.getString("password");
                       String s7=rs.getString("emailid");
                        String s8=rs.getString("course_id");
                 
                  Vector cell=new Vector();
                  cell.add(s1);
                  cell.add(s2);
                
                 
                  row.add(cell);
                 
                
              }
                DefaultTableModel model=new DefaultTableModel(row,heading);
           ttt.setModel(model);    con.close();
              }
    
    catch(Exception ex)
    {
        ex.printStackTrace();
    }
   }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cb1;
    private javax.swing.JComboBox cb2;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTable ttt;
    private javax.swing.JTable ttt1;
    // End of variables declaration//GEN-END:variables
}
