
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class studentattendance extends javax.swing.JInternalFrame {

    /**
     * Creates new form studentattendance
     */  ArrayList course=new ArrayList();
  ArrayList subject=new ArrayList();
   ArrayList student_pr=new ArrayList();
   boolean flag;
   boolean flag1;
    String uname_1;
    String sid2;
    String cid;
    public studentattendance(String uname,String sid1) {
        initComponents();
            uname_1=uname;
       cid=sid1;
        
      
                    flag=true;
                    flag1=true;
                   
                //  cid=  fillcourses();
                  System.out.println("COURSE ID :"+cid);
                   fillsubjects();
                   
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cb1 = new javax.swing.JComboBox();
        cb2 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("Course ID");

        jLabel2.setText("Subject ID");

        cb1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb1ItemStateChanged(evt);
            }
        });

        jLabel3.setText("Student attendance is");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(103, 103, 103)
                            .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(45, 45, 45)
                        .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb1ItemStateChanged
        // TODO add your handling code here:
           if(flag != false)
        {
           
           int count=2;
        }
    }//GEN-LAST:event_cb1ItemStateChanged

public String fillcourses()
{
    String courseid1="";
      try
         {
             
//           
//      String d_array[] = new String[2];
//              int id=cb1.getSelectedIndex();
//          String c[]=   (String [])course.get(id);
//          String course_id = c[0];
          
              Class.forName("oracle.jdbc.OracleDriver");
          String str = "jdbc:oracle:thin:@localhost:1521:";
          Connection con = DriverManager.getConnection(str,"ANKITA","ANKITA");
                String s="select * from student_pr where sid=?";

          PreparedStatement ps=con.prepareStatement(s);
       
             System.out.println("STUDENT ID "+sid2);
            ps.setString(1, sid2);
          ResultSet rs=ps.executeQuery();
          
          if(rs.next()){
            courseid1=rs.getString("course_id");
         }
          
         
          
          con.close();
          
         }
         catch(Exception e)
         {
             e.printStackTrace();
         }
      return courseid1;
    
}
 void fillsubjects()
    {
         try{
              cb2.removeAllItems();
              if(flag !=false)
              {
              Class.forName("oracle.jdbc.OracleDriver");
          String str = "jdbc:oracle:thin:@localhost:1521:";
          Connection con = DriverManager.getConnection(str,"ANKITA","ANKITA");
          String s="select * from subject where course_id=?";
          PreparedStatement ps=con.prepareStatement(s);
      
        ps.setString(1,cid);
          
         ResultSet rs= ps.executeQuery();
         while(rs.next()){
             String sub_array[]=new String[3];
             sub_array[0]=rs.getString("subject_id");
             sub_array[1]=rs.getString("subject_name");
              sub_array[2]=rs.getString("course_id");
            String cname=rs.getString("subject_name");
            subject.add(sub_array);
            cb2.addItem(cname);
         }
          flag1=true; con.close();
              }
           
    }
    catch(Exception e){
        e.printStackTrace();
    }
         
    }
 public void presentattendance()
 {
     try
     {
               Class.forName("oracle.jdbc.OracleDriver");
          String str = "jdbc:oracle:thin:@localhost:1521:";
          Connection con = DriverManager.getConnection(str,"ANKITA","ANKITA");
        String q="select * fron attendance where sid=? and subject_id=?" ;
         PreparedStatement ps=con.prepareStatement(q);
       int id1=cb2.getSelectedIndex();
          String sid[]= (String []) subject.get(id1);
          String sidd=sid[0];
        ps.setString(1,cid);
        
          ps.setString(1,sidd);
     }
    catch(Exception e){
        e.printStackTrace();
    }
 }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cb1;
    private javax.swing.JComboBox cb2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField t1;
    // End of variables declaration//GEN-END:variables
}
